Add clangarm64

diff --git a/msys2-dbremove b/msys2-dbremove
--- a/msys2-dbremove
+++ b/msys2-dbremove
@@ -40,9 +40,12 @@ then
 elif [ "${repo}" = "clang32" ]
 then
     update_packages clang32 "mingw/clang32" "${@}"
+elif [ "${repo}" = "clangarm64" ]
+then
+    update_packages clangarm64 "mingw/clangarm64" "${@}"
 elif [ "${repo}" = "msys" ]
 then
     update_packages msys "msys/x86_64" "${@}"
 else
-    echo "Missing or unrecognized first argument: msys|mingw32|mingw64|ucrt64|clang64" >&2
+    echo "Missing or unrecognized first argument: msys|mingw32|mingw64|ucrt64|clang64|clang32|clangarm64" >&2
 fi
