Handle some error conditions better

diff --git a/update-installer b/update-installer
--- a/update-installer
+++ b/update-installer
@@ -1,12 +1,20 @@
 #!/bin/bash
-# Usage: ./update-installer 2021-02-28
 
 set -e
 
 pub=/srv/msys2repo
 
+if test -z "${1}"
+then
+    echo "Missing installer release date." >&2
+    echo "Example usage: ${0} 2021-02-28" >&2
+    exit 1
+fi
+
+RELEASE="${1}"
+shift
+
 cd "${pub}/distrib/x86_64/"
-RELEASE="$1"
 curl --fail -sLO "https://github.com/msys2/msys2-installer/releases/download/${RELEASE}/msys2-base-x86_64-${RELEASE//-/}.tar.xz"
 curl --fail -sLO "https://github.com/msys2/msys2-installer/releases/download/${RELEASE}/msys2-base-x86_64-${RELEASE//-/}.tar.xz.sig"
 curl --fail -sLO "https://github.com/msys2/msys2-installer/releases/download/${RELEASE}/msys2-x86_64-${RELEASE//-/}.exe"
